### ISSUE TITLE
How to set other DCMTK options

### ISSUE THREAD

**Issue by helghast79** [knopkem/dicom-dimse-native#10]
Thanks for great work!

Just wondering how to set other network options available in DCMTK, for example proposed or preferred transfer syntaxes.
In my case I have an error on moveScu which sends message 

> unable to convert dataset from 'RLE Lossless' transfer syntax to 'Little Endian Explicit'

I believe setting some options will allow this kind of problems to be solved.

**Comment by knopkem** [comment]
Hi,
unfortunately currently there is no way to set those options but you are right they are useful, shouldn't take long to add. Will update this thread once done. Happy eastern.

**Comment by knopkem** [comment]
Hi,
I added the following new properties to the config options:
```
"netTransferPrefer": "1.2.840.10008.1.2.4.80", // preferred network transfer syntax (accepted ts - additional to default ts)
"netTransferPropose": "1.2.840.10008.1.2.4.80", // proposed network transfer syntax (for outgoing associations - additional to default ts)
"writeTransfer": "", // write transfer syntax (storage only, recompress on the fly), keep empty to store ts as original
```
See the updated examples. I was able to perform a c-move to itself (storescp) from Clearcanvas ussing RLE lossless. 
For the moment this is only in the master and there is no new npm version yet, this will come later.
If you still have issues, please be specific about what exactly you performed including a full log.

**Comment by helghast79** [comment]
Thanks for this. 
Will test this soon and give some feedback. One more thing btw, is there a way to stop the SCP without killing the parent process?

**Comment by helghast79** [comment]
Seems working for all images I have at the moment. Can't say if it works in all cases but at least, there is now some options to try to correct things.

cheers

**Comment by geezer78** [comment]
Hi all, it would be usefull to provide an array of transfer syntaxes on a C-move request and have them be negotiated. that way it would be possible to have the system fallback without catching errors (what i do now)

**Comment by knopkem** [comment]
Ok, seems like this would be a good improvement. Will add it soon
