### ISSUE TITLE
How to stop SCP?

### ISSUE THREAD

**Issue by helghast79** [knopkem/dicom-dimse-native#11]
Hello,

How to stop SCP without killing the parent process?

**Comment by knopkem** [comment]
Hi,
this is not yet integrated. Will check if I can add it.

**Comment by helghast79** [comment]
Hi there,
Any update on this?
It would be great if we could comunicate with the process running like send events for specific actions like get errors, logs, stop or restart commands

**Comment by knopkem** [comment]
Sorry, didn't have the time yet, but will try to look at this now.

**Comment by knopkem** [comment]
Hi, I released a new version that adds a shutdownscu example. This is the way dcmtk implements the threaded server shutdown. Basically when it receives a private shutdown command it stops the event loop and terminates.
The other projects dicomweb-proxy and dicomweb-pacs now use this which you can take as an example.

**Comment by helghast79** [comment]
Hi, it works and we can now stop the SCU without killing the parent script. With my setup I had to config the shutdownscu call to the other pacs as source and the one being shutdown as target. I suppose this is normal right?

On a success shutdown SCU sends 2 responses as listed below:

- {"code":1,"container":null,"message":"Requesting Association","status":"pending"}
- {"code":2,"container":null,"message":"Association Rejected: Result: Rejected Permanent, Source: Service User\nReason: No Reason","status":"failure"}

despite the failure status, the end result is that SCU is stopped so mission accomplished. Thank you :)

**Comment by knopkem** [comment]
Yes, this is how it is supposed to be used. And yes, the error message is normal and comes from dcmtk.
