### ISSUE TITLE
Alpine prebuilt binaries?

### ISSUE THREAD

**Issue by william00179** [knopkem/dicom-dimse-native#12]
Hi,
I would like to use your package, but would like to avoid having to install g++ in our container to compile it. Would you consider adding an Alpine linux (musl) pre-built binary?

> dicom-dimse-native@1.2.14 install /usr/src/app/node_modules/dicom-dimse-native
> prebuild-install -r napi || cmake-js compile

prebuild-install WARN install No prebuilt binaries found (target=4 runtime=napi arch=x64 libc=musl platform=linux)
[
  '/usr/local/bin/node',
  '/usr/src/app/node_modules/.bin/cmake-js',
  'compile'
]
ERR! OMG C++ Compiler toolset is not available. Install proper compiler toolset with your package manager, eg. 'sudo apt-get install g++'.

**Comment by knopkem** [comment]
Hi,
I must confess that I've never heard of alpine linux before. The libc difference is the problem here, will play with it in a VM and let you know. Once everything works I can add it to the build machines, no problem.

**Comment by william00179** [comment]
I spun up an Alpine container and built the binaries and published them for now to a fork. 

https://github.com/william00179/dicom-dimse-native/releases/tag/v1.2.14

and overrode the binary host in my npmrc

dicom-dimse-native_binary_host=https://github.com/william00179/dicom-dimse-native/releases/download

No issues (that I noted) during compiling, but when trying to use the module, I get the following

Error: Error relocating /usr/src/app/node_modules/dicom-dimse-native/build/Release/dcmtk.node: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev: symbol not found

I'm not up to speed with cmake to be able to investigate why this might be cropping up

**Comment by william00179** [comment]
On the above, this issue was resolved when I compiled on the older version of Alpine that our production container is currently using, not Alpine latest. There must be an API change between the two versions.

**Comment by knopkem** [comment]
So, just to make sure I understood correctly:
- When building with older alpine release it works on the old version *and on the latest* (?)
- When building with latest alpine release it compiles but doesn't work (even on latest) with the error above
I only know for standard libc that it's usually advisable to use a rather old version as newer versions are backwards compatible in order to make it compatible with a broader range of os (which is what I do, using an old centos 6).
So personally I think we should do the same with alpine. Am I right?

**Comment by knopkem** [comment]
In the end I used alpine 3.9.6 for the build as this is the first version that comes with npm 6. It's from 2018 so should hopefully work for most cases. It should work with all version >= 3.9 (but not below). Let me know if this helps.

**Comment by william00179** [comment]
@knopkem working well with the Alpine binaries you built. Thanks!
