### ISSUE TITLE
Configure presentation context for storeScu

### ISSUE THREAD

**Issue by sgsfak** [knopkem/dicom-dimse-native#19]
Using the storeScu example with a DICOM-SEG file results in the following error:

```
I: ======================= END A-ASSOCIATE-AC ======================
I: Association Accepted (Max Send PDV: 16372)
I: Sending file: Slicer/tumor_User1_Manual_Trial1.dcm
D: DcmDataDictionary: Loading file: /usr/local/share/dcmtk/dicom.dic
D: DcmMetaInfo::checkAndReadPreamble() TransferSyntax="Little Endian Explicit"
D: DcmDataset::read() TransferSyntax="Little Endian Explicit"
E: No presentation context for: (SG) 1.2.840.10008.5.1.4.1.1.66.4
I: C-Store progress: 100
E: 0006:0208 DIMSE No valid Presentation Context ID
```

The same error is returned when I use the command line `storescu` from DCMTK but it can be solved by adding the "unknown" presentation context ([1.2.840.10008.5.1.4.1.1.66.4](http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_A.51.html)) in the config file used, as described [here](https://book.orthanc-server.com/faq/dcmtk-tricks.html). Or just use `dcmsend` 

How we can do the same with this package?

Thank you so much!

**Comment by knopkem** [comment]
Hi, currently there is no similar way to do this, however this is an interesting point, will try to come up with a solution for it

**Comment by knopkem** [comment]
I changed the code to use the logic of dcmsend instead of storescu which seems to work for me now. Let me know if there are any issues. cheers. Npm version 1.3.1

**Comment by sgsfak** [comment]
It works fine! Thank you!
