### ISSUE TITLE
Support modality worklist database server？

### ISSUE THREAD

**Issue by javapon** [knopkem/dicom-dimse-native#21]
Hi
Test the modality worklist database server failed. Can the later version integrate this server?Thanks!

**Comment by knopkem** [comment]
Sorry, there is no Worklist SCP implemented. Pars are welcome though.

**Comment by javapon** [comment]
This project is very good, if  have Worklist SCP , can really replace the dcm4che or dcmtk.

**Comment by knopkem** [comment]
I agree Worklist is useful, I'll put in on the roadlist

**Comment by cultulhul** [comment]
any updates on implementing modality worklist

**Comment by knopkem** [comment]
Hi, unfortunately not. Didn't have the time for it lately, sorry.
