### ISSUE TITLE
getSCU uses source.aet both for called and for calling aettile 

### ISSUE THREAD

**Issue by albertosaez** [knopkem/dicom-dimse-native#26]
getSCU has an error setting the peer's aetitle,  it should use the target aet, not the source aet.

File src/GetAsyncWorker.cc line 213

![image](https://user-images.githubusercontent.com/3266240/141677248-5a16f62d-ce24-4bb8-b908-4f6e58a3dd53.png)

scu.setPeerAETitle(in.source.aet.c_str());   

....   Should be 

scu.setPeerAETitle(in.target.aet.c_str());

**Comment by knopkem** [comment]
Thanks, will change it asap

**Comment by knopkem** [comment]
Fixed in 2.0.1
