### ISSUE TITLE
error message 

### ISSUE THREAD

**Issue by muratdogan1** [knopkem/dicom-dimse-native#29]
npm run example:[echoscu|findscu|getscu|movescu|storescu|storescp]   error

C:\dicom-dimse-native>npm run example:[echoscu|findscu|getscu|movescu|storescu|storescp]
'findscu' is not recognized as an internal or external command,
operable program or batch file.

**Comment by knopkem** [comment]
Strange.
What is your Nodejs version?

**Comment by muratdogan1** [comment]
C:\dicom-dimse-native>node -v
v12.16.2

**Comment by knopkem** [comment]
I suspect it's caused by ts-node (typescript running in nodejs directly), although it seems that it should support node12. Can you try with latest LTS? Otherwise you could still use plain js. (Similar syntax, look at [dicomweb-pacs](https://github.com/knopkem/dicomweb-pacs) for usage)

**Comment by muratdogan1** [comment]
I upgraded but still the same
C:\dicom-dimse-native>node -v
v16.13.2

**Comment by knopkem** [comment]
Since I can't reprduce it and it's not related to nodejs version. Please try if dicomweb-proxy (uses typescript import of dicom-dimse-native) and dicomweb-pacs (javascript imports) work. Not sure how to help further.

**Comment by knopkem** [comment]
Ok, I know what the issue is:
You ran "npm run example:[echoscu|findscu|getscu|movescu|storescu|storescp]" however this is just a place holder notation.
You should run: "npm run example:findscu" or "npm run example:echoscu"
