### ISSUE TITLE
Unable to use module

### ISSUE THREAD

**Issue by kadeem220** [knopkem/dicom-dimse-native#34]
I am trying to use this module in a Vue3 + Vuex + Electron project. My problem is that I can't import it and use it. All I am trying to do is a C-ECHO from my app.
Can I get some advice please on this? 

If I go into the node_modules\dicom-dimse-native and run "npm run example:echoscu" I am able to see that it is working and see results. So basically running the echoscu.ts file works fine.

In my app i am trying to do the following:
![image](https://user-images.githubusercontent.com/66702038/164735785-dae052a4-3f85-4c92-b07a-1a2364e7bfb7.png)

The problem is that it fails to load the module. I have googled and tried many things but no success.
![image](https://user-images.githubusercontent.com/66702038/164736944-3a64f758-8890-45f1-b024-c0d0b212f449.png)

It is the first time when I use this kind of module that uses c++ and I know I am doing something wrong here. Anything that could help me use it would be highly appreciated.
Thank you

**Comment by knopkem** [comment]
Hi,
you are not the first with this issue and unfortunately I never got it to work with electron (and vercel/pkg -> same issue).
I tried all the recommendations from here: https://github.com/nodejs/node-addon-api/issues/269
