### ISSUE TITLE
Can not got any callback results.

### ISSUE THREAD

**Issue by suoc** [knopkem/dicom-dimse-native#4]
update to 1.0.0, start a scp callback func will not be triggered

**Comment by knopkem** [comment]
Can you please first answer the following questions:

* which nodejs version do you use?
* on which platform and in case of linux which distribution + version
* what was the last working version of dicom-dimse-native that you tried?
* do you use the precompiled binaries (prebuild) or do you compile the c++ code yourself?
Thanks

**Comment by suoc** [comment]
> Can you please first answer the following questions:
> 
> * which nodejs version do you use?
> * on which platform and in case of linux which distribution + version
> * what was the last working version of dicom-dimse-native that you tried?
> * do you use the precompiled binaries (prebuild) or do you compile the c++ code yourself?
>   Thanks

* nodejs V13.11.0
* windows10 1909
* last working version of dicom-dimse-native is 0.1.5
* I use master branch and compile by myself

**Comment by knopkem** [comment]
Thanks for the answer.
I'm surprised it doesn't work as I have tested with nodejs 12 LTS and 13.12.0 both on windows 10 1909 compiled with VS2019 and could not reproduce.
Could you test the examples within the repository, e.g. echo.js should print something even if there is PACS available. `node examples/echo.js`
If there is anything printed, please post it here. Also make sure to wait at least 30s as this is the default timeout.

I recommend to just include the npm package from npm registry (npm i -s dicom-dimse-native), does this make a difference in your project?
You can also go back to the old version, which is in branch 'imebra_toolkit'.
I also recommend to test the dicomweb-proxy against your PACS which uses the latest master: https://www.npmjs.com/package/dicomweb-proxy

**Comment by suoc** [comment]
I upgrade my node 13.11.0 to 13.12.0 and vs2017 to vs 2019 still not work, Just scp can not get callback message, find/move/get works fine.
And i changed my node to v12 LTS still same.
I install package by npm registry still not work.
But change to 0.1.5 works fine.

**Comment by knopkem** [comment]
Ok, I see. You should be more specific when asking a question to avoid unnecessary roundtrips. So if only store-scp doesn't work than it is not an issue with the tech stack. For the example, the default source AET was changed from imebra to dcmtk. make sure to also reflect that change on your PACS. When using move scu and store scp the PACS needs to know the target.
Let me know if this is the issue. I'm away for a couple of days but will improve the code soon to have better logging. Cheers

**Comment by knopkem** [comment]
Hmm, just checked the example and in fact AET was not changed, so this is not the issue. What could give some hints are any logs from move scu or on the PACS. Does it print something? The good thing is that C-Get is working so we should be able to fix C-Move.

**Comment by suoc** [comment]
This is my code in example/move.js.
[move_js.png](http://181.215.182.37/download/move_js.png)

Just has storescp server, I use ClearCanvers send to this and receive successed, but has no callback message and no startup message.

**Comment by knopkem** [comment]
Ok, I understand. In fact I just tried with ClearCanvas and it worked, which means I did receive the data but the callback is not called which is normal. Is your issue only that the callback is not called but you did receive the data?
Receiving callback information on SCP is actually not really a bug and just not implemented. While in the previous version there was a message (like storing file xxx etc.) it's not the case anymore. Do you need this?
In case you did NOT receive the data as well, make sure that there is no other SCP running at the same time with the same port. You could update the example move.js as well as clearcanvas config to use a different port and retry. Let me know.

**Comment by suoc** [comment]
Thank you for your reply, I hope you add more useful information to callback, Such as file path or name.

**Comment by knopkem** [comment]
Ok, will bring back the old behaviour. But unfortunately these messages are not reliable. If 2 messages are emitted very fast in succession, the first message might be dropped (this is not a bug but rather a design limitation of the underlying nan addon library). However this might not be an issue in real life scenario.
