### ISSUE TITLE
Binaries for darwin-arm64?

### ISSUE THREAD

**Issue by Sergio-P** [knopkem/dicom-dimse-native#43]
I have used this library in linux x64 without problems, but now I'm working in a macbook air with apple silicon, so the architechture is darwin-arm64 and I didn't find any binaries for this target. I tried to compile to the code using cmake and gcc/g++ but it didn't work and the error trace is very large to post it here. Is there any possibility to have a binary for this target, or do you have any advice to compile it?

**Comment by knopkem** [comment]
Hi,
unfortunately I don't have access to an M1 so can't produce the binaries for it. I would suggest starting to try compiling latest DCMTK first. If this works try 3.6.6 (which is the base for dicom-dimse-native). This might be helpful: https://groups.google.com/g/orthanc-users/c/QDeNjKLcEBA
Good luck

**Comment by Sergio-P** [comment]
Thanks for the response. I will follow these instructions, if I have success I can share the binary.
