### ISSUE TITLE
DCMTK Version?

### ISSUE THREAD

**Issue by ajbatta** [knopkem/dicom-dimse-native#45]
What is the DCMTK version used in this library? Also, is it kept up to date?

**Comment by knopkem** [comment]
Version is 3.6.6 Will update to 3.6.7 soon

**Comment by ajbatta** [comment]
Awesome, thanks for the info! Is this documented anywhere in the repo?On Oct 8, 2022, at 3:45 AM, Michael Knopke ***@***.***> wrote:﻿
Version is 3.6.6 Will update to 3.6.7 soon

**Comment by knopkem** [comment]
No, it's not but will do with the next update. Cheers.

**Comment by knopkem** [comment]
I was trying to update to 3.6.7 (there is a branch in this repo for it) and it almost worked. But somewhere in the depths of DCMTK CMake (on windows only as far as I recollect) was adding a library dependency (forget which one) that I could not associate or even locate. After wasting a lot of time (as Configuring CMake for DCMTK on Windows takes ages) I gave up and forgot about it, sorry. Not sure how to proceed, maybe someone with more CMake experience could help here.

**Comment by knopkem** [comment]
@ajbatta I finally found the time to upgrade dcmtk version. It is now based on dcmtk 3.6.8 (latest) and this is now tracked on the main readme.

**Comment by ajbatta** [comment]
Awesome!Thank you for the update!On Jan 30, 2024, at 4:05 AM, Michael Knopke ***@***.***> wrote:﻿
@ajbatta I finally found the time to upgrade dcmtk version. It is now based on dcmtk 3.6.8 (latest) and this is now tracked on the main readme.
