### ISSUE TITLE
PN elements not correctly encoded in JSON when running on Linux (CentOS)

### ISSUE THREAD

**Issue by nicovn** [knopkem/dicom-dimse-native#47]
Hi,

I have a very strange issue, when running dicom-dimse-native on linux; the PN attributes are incorrectly encoded in the JSON message.

We have an array too much in the Value. 

Example result:

`[
  {
    "00080052": {
      "Value": [
        "STUDY"
      ],
      "vr": "CS"
    },
    "00100010": {
      "Value": [
        [
          {
            "Alphabetic": "Vannieuwenhuyze^Nico"
          }
        ]
      ],
      "vr": "PN"
    },
    "00100020": {
      "Value": [
        "7406121003"
      ],
      "vr": "LO"
    }
  }
]`

It is caused by the statement below on line 270 in FindAsyncWorker.cc - https://github.com/knopkem/dicom-dimse-native/blob/master/src/FindAsyncWorker.cc

jsonValue.push_back({json{{"Alphabetic", value}}});

when modified to "jsonValue.push_back(json{{"Alphabetic", value}});" the result is OK, but I don't know if this has any other impact ?

Thanks for your feedback !

Best Regards

Nico

ps: also interested in the dcmtk upgrade to 3.6.7 (which includes also the functionality to encode as JSON)

**Comment by knopkem** [comment]
hi, thanks for the report, will have a look at this asap.

**Comment by nicovn** [comment]
Hi Michael,


Thanks for your feedback and follow-up !

No worries about the delay ;-)

Best Regards

Nico

Op vr 14 apr 2023 om 17:27 schreef Michael Knopke ***@***.***

**Comment by knopkem** [comment]
Should be fixed now
