### ISSUE TITLE
100% CPU right on the start

### ISSUE THREAD

**Issue by wagner87** [knopkem/dicom-dimse-native#52]
Do you have any problems with CPU? I simple start my storeScp with some options and my CPU goes to 100%.

Here is my code:

``` 
const StoreScpOptions: storeScpOptions = {
        source: {
            aet: AppService.getInstance().loggedBeeRadsBox.pacsConfig.aeTitle,
            ip: '127.0.0.1',
            port: AppService.getInstance().loggedBeeRadsBox.pacsConfig.port,
        },
        peers: [
            {
                aet: AppService.getInstance().loggedBeeRadsBox.pacsConfig.aeTitle,
                ip: '127.0.0.1',
                port: AppService.getInstance().loggedBeeRadsBox.pacsConfig.port + 1,
            }
        ],
        storagePath: './',
        netTransferPrefer: '1.2.840.10008.1.2.4.80', // preferred network transfer syntax (accepted ts - additional to default ts)
        netTransferPropose: '1.2.840.10008.1.2.4.80', // proposed network transfer syntax (for outgoing associations - additional to default ts)
        writeTransfer: '', // write transfer syntax (storage only, recompress on the fly), keep empty (or leave out) to store ts as original
        permissive: false, // if true any AET can perform FIND,GET and STORE
        verbose: false,
        storeOnly: true, // do not provide FindSCP and MoveSCP (requires db) only StoreSCP
        writeFile: false, // do not write file to disk, send via buffer as base64 in response (only taken into account when storeOnly is true)
    }

    // StoreSCP que aguarda recebimento das imagens
    startStoreScp(StoreScpOptions, async (result) => {
        console.log('result', {result});
    })
```

**Comment by knopkem** [comment]
Hi, never had this before. Can you try the dicomweb-pacs from my repos to see if you get the same issue?

**Comment by knopkem** [comment]
Also, what is and CPU is this running on?

**Comment by wagner87** [comment]
Hello, Michael. Thank you for the answer.

I was running on a Macbook Pro with 2,3 GHz 8-Core Intel Core i9.

Sure, I will try dicomweb-pacs. Is it possible to use dicomweb-pacs with
compression? If yes, do you have any tutorial? I will need compress and
send images to AWS S3 bucket.
Wagner Bitencourt
CTO & Founder, Nerit
*Tel:* +55 (31) 3047.5405
*Tel:* +55 (11) 4380.6606
*Email:* ***@***.***
*Skype:* nerit.tecnologia

**Comment by knopkem** [comment]
Hi, to be honest, MacOS isn't tested well (just compiled and checked that it did some basic stuff) but would still be surprised with the high load, let's see how dicomweb-pacs works for you. Also, you can run the samples within this repo, one of them also spawns the server.

Regarding compression: I guess you mean DICOM image compression. Currently compression in dicomweb-pacs is only used like this:
* connected peers can send compressed images and images are stored as is (not uncompressed) if compression is supported
* when using the viewer, images are compressed on the fly depending on the config setting (look for transferSyntax). The TS defines how the image is transferred (or stored) see https://www.dicomlibrary.com/dicom/transfer-syntax/
* usually JPEG-LS Lossless Image Compression is best regarding speed and compression ratio, JPEG2000 might give slightly better ratio but is a lot slower (with the available open source library used)
* have a look at the compression sample in this repo
Cheers
