### ISSUE TITLE
TooManyAssociations?

### ISSUE THREAD

**Issue by grfityhero** [knopkem/dicom-dimse-native#53]
Hi,
What could be the reason for " Refusing Association (TooManyAssociations)" ,Node js  on ubuntu 20.
this happens only on the 4th or 5th study and give error in dul , all the other studies -no problem.
Thanks! (v2.4.0 -)

**Comment by knopkem** [comment]
Hi, can you specify what you do exactly. E.g. using c-find on other PACs or do you query the internal server?

**Comment by knopkem** [comment]
closing issue as there was no answer. Basically, "too many associations" means that the server cannnot handle any more incoming requests (this might be a setting in dcmtk, not sure) and just rejects any new requests until the current open assocs are closed. Associations in DICOM are similar to requests in http.
