### ISSUE TITLE
How to re-compile the project

### ISSUE THREAD

**Issue by allandiegoasilva** [knopkem/dicom-dimse-native#55]
How I can compile the project c++ again? 
I am trying but don't have success. 

I am using `cmake `

**Comment by knopkem** [comment]
Hi, what is your OS? Provided you have CMAKE and a working (modern) c++ compiler installed, you should first clone the repo than install dependencies and then run "npm run compile". You can print any output here for guidance. Cheers

**Comment by allandiegoasilva** [comment]
I got this error when I will compile: 

[Image with error](https://prnt.sc/9yFlGZhCXQXE) 

My computer
- Windows 10 x64
- Cmake v3.26.3
- Node v18.14.2

I'll parse the library for `MySQL` do you have interest for merge in your project?

**Comment by knopkem** [comment]
Sorry forgot about this issue. Did you solve it? The error you showed, does this happen with the latest master (unmodified). Which compiler (vs) do you use?

**Comment by knopkem** [comment]
I updated the project to the latest dcmtk version, it should compile out of the box once, you got the prerequisites. Tested with:
* VS community 2022 cpp compiler
* CMake 3.28.1
* Node V18.18.0
* Win 11
Reopen, if you still experience issues.
