### ISSUE TITLE
Doesn't work with M1 chip Mac

### ISSUE THREAD

**Issue by emelalkim** [knopkem/dicom-dimse-native#59]
The library doesn't work on a Mac with M1 chip. Is there a way that I can configure it to work?

**Comment by knopkem** [comment]
The M1 uses ARM architecture and currently the only precompiled binaries are for x86_64. In theory you could try to build it yourself but first I'm not sure if the underlying DCMTK toolkit really compiles for this architecture (I doubt it) and secondly this is not a trivial process (anymore) given the additional dependencies that you would also need to provide.
So your best shot is to use node with Rosetta and emulate x86_64, then everything should work (in theory):
https://gist.github.com/LeZuse/bf838718ff2689c5fc035c5a6825a11c

I don't have an M1/2 so can't test (but it's on my wishlist...on day) .
Cheers and good luck

PS: If you manage to run it, please describe your process here for others to benefit. Thank you
Michael
