### ISSUE TITLE
startScp

### ISSUE THREAD

**Issue by bmkimagem** [knopkem/dicom-dimse-native#6]
Hi, I did some tests and it works well ... congratulations ...
Is there a way to use fork child process for each association to use multi-process options?

**Comment by knopkem** [comment]
Thanks.
while I can see the benefit in this scenario I don't think there is a simple solution here. The project currently uses the nodejs addon api - NAN (or better c++ addon) and relies on the build in worker thread model. Forking would require an executable which makes things platform specific. I'm by no means an expert regarding NAN but from a quick glance over the api I couldn't see a way.
I only use this code for a dicomweb proxy and the simplest way to avoid spawning too many threads is to use a request queue in js land, however when using it as a PACS the only way I see is to hard limit the allowed number of concurrent associations.
When forking is really needed, there is another project https://github.com/jmhmd/dcmtk-node which simply wraps executables, here one can use forking easily (dcmtk has examples regarding this afaik) but setup is more complicated. Hope I could help.

**Comment by bmkimagem** [comment]
I use dcm4che as a router, and I tested your application. In the dcmtk binary, just run storescp with --fork at the end.
I tested this same process on yours, but to no avail.

**Comment by knopkem** [comment]
Yes, this is not implemented and won't be in the future, sorry

**Comment by bmkimagem** [comment]
No problem, but it's getting really good ...
