### ISSUE TITLE
startStoreScp prints a lot of log to terminal even thought I set verbose = false || startStoreScp is also low compared to dcmtk

### ISSUE THREAD

**Issue by PotatoThanh** [knopkem/dicom-dimse-native#65]
Hi,

It would be  nice to know how to turn off the console when StoreScp is receiving dicom files. It runs really slow as well. Thanks!

.....
cmFileFormat::checkMetaHeaderValue() use SOPInstanceUID [1.3.12.2.1107.5.1.4.91007.3000002208022330229870002387991] from Dataset
D: DcmFileFormat::checkMetaHeaderValue() use new TransferSyntaxUID [Little Endian Explicit] on writing following Dataset
D: DcmFileFormat::validateMetaInfo() found 7 Elements in DcmMetaInfo 'metinf'
D: DcmFileFormat::checkMetaHeaderValue() Version of MetaHeader is ok: 0x0001
D: DcmFileFormat::checkMetaHeaderValue() use new TransferSyntaxUID [Little Endian Explicit] on writing following Dataset
D: DcmFileFormat::validateMetaInfo() found 7 Elements in DcmMetaInfo 'metinf'
D: DcmDataset::read() TransferSyntax="Little Endian Implicit"
D: DcmDataset::read() TransferSyntax="Little Endian Explicit"
D: DcmFileFormat::checkMetaHeaderValue() Version of MetaHeader is ok: 0x0001
D: DcmFileFormat::checkMetaHeaderValue() use SOPClassUID [1.2.840.10008.5.1.4.1.1.2] from Dataset
D: DcmFileFormat::checkMetaHeaderValue() use SOPInstanceUID [1.3.12.2.1107.5.1.4.91007.3000002208022330229870002392191] from Dataset
D: DcmFileFormat::checkMetaHeaderValue() use new TransferSyntaxUID [Little Endian Explicit] on writing following Dataset
D: DcmFileFormat::validateMetaInfo() found 7 Elements in DcmMetaInfo 'metinf'
D: DcmFileFormat::checkMetaHeaderValue() Version of MetaHeader is ok: 0x0001
D: DcmFileFormat::checkMetaHeaderValue() use new TransferSyntaxUID [Little Endian Explicit] on writing following Dataset
D: DcmFileFormat::validateMetaInfo() found 7 Elements in DcmMetaInfo 'metinf'
D: DcmDataset::read() TransferSyntax="Little Endian Implicit"

**Comment by knopkem** [comment]
Hi, this is related to https://github.com/knopkem/dicom-dimse-native/issues/61
Will try to implement the log forwarder.

**Comment by PotatoThanh** [comment]
Yes, thank you very much!

**Comment by knopkem** [comment]
@PotatoThanh It's strange that verbose= false did print Debug and Info messages for you, as I use this in my other projects (dicomweb-pacs and proxy). Anyway, I changed the log appender to use the roling file appender, which now does not print to the console but to a file called dicom.log (max 10mb) This should solve your speed issues.

**Comment by PotatoThanh** [comment]
@knopkem thank you for your reply. I think your new build version ^2.4.5 has a bug. I could not receive any thing using storeSCP.

console log show:
DIMSE failure (aborting association): Data dictionary missing

dicom.log
ERROR [09-02-2024 04:24:14:109]: DcmDataDictionary: Cannot open file: /usr/local/share/dcmtk-3.6.8/dicom.dic

**Comment by knopkem** [comment]
Thanks for reporting. Seems like the option to use the built-in dictionary is not enabled. Will fix this soon.

**Comment by PotatoThanh** [comment]
Thank you!!!

**Comment by knopkem** [comment]
I published a new version. Can you try again?

**Comment by PotatoThanh** [comment]
All good for me. Thank you!!
