### ISSUE TITLE
Invalid access to memory location

### ISSUE THREAD

**Issue by superSun88** [knopkem/dicom-dimse-native#9]
when i use this module on electron-vue
i have installed dicom-dimse-native module, but got an error when i 'require('dicom-dimse-native')'.
----------error:
vue.esm.js?efeb:1897 Error: Invalid access to memory location.
\\?\.../node_modules\dicom-dimse-native\build\Release\dcmtk.node

**Comment by knopkem** [comment]
Googling this issue it seems that electron has issues with dependencies that use the native api. Sorry, can't help here.
